# Generated by Django 4.2 on 2023-04-19 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_id', models.SmallIntegerField(default=0)),
                ('Name', models.CharField(db_index=True, max_length=255)),
                ('No_of_guests', models.PositiveIntegerField(default=1)),
                ('BookingDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_id', models.SmallIntegerField(default=0)),
                ('Title', models.CharField(db_index=True, max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Inventory', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
